apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-server-config-cpu
data:
  vllm-eval-config.json: |
    {
      "configs": [
        {
          "accelerator": "cpu",
          "model": "Qwen/Qwen2.5-0.5B-Instruct",
          "vllmServedModelName": "qwen",
          "vllmPort": 8000,
          "warmupSec": 30,
          "minWindowSec": 60,
          "maxWindowSec": 300,
          "targetSamples": 20,
          "minSamples": 5,
          "ignoreEOS": true,
          "queueTimeMetric": "vllm:request_queue_time_seconds"
        }
      ]
    }
